/* Konten nurunala — dipakai bersama oleh index, baca, buku */

var coverStyles=[
  {bg:'#dce8e2',stripe:'#9ac4b0'},{bg:'#e8e2dc',stripe:'#c4a990'},{bg:'#dce2e8',stripe:'#90a9c4'},
  {bg:'#e8dce2',stripe:'#c490a9'},{bg:'#e2e8dc',stripe:'#a9c490'},{bg:'#e8e8dc',stripe:'#c4c490'},
  {bg:'#dce8e8',stripe:'#90c4c4'},{bg:'#e8dcdc',stripe:'#c49090'},{bg:'#e2dce8',stripe:'#a990c4'},
  {bg:'#e8e2dc',stripe:'#c4b090'},{bg:'#dce2e2',stripe:'#90b0b0'},{bg:'#e4dce8',stripe:'#b090c4'},
];

var allPosts=[
  {date:'21 April 2025',title:'Memelihara Harapan',excerpt:'Elang bilang harapan bukan soal yakin sesuatu akan berhasil. Tapi soal mau tetap ada, meski tidak tahu.',body:`<p>"Kamu masih berharap?" tanya Rana. Nada suaranya bukan meremehkan — lebih seperti orang yang benar-benar ingin tahu jawaban yang jujur.</p><p>Elang menatap kopinya sebentar. Di luar, hujan turun pelan, jenis yang tidak dramatis tapi juga tidak berhenti-berhenti.</p><p>"Iya," katanya akhirnya.</p><p>"Kenapa? Bukannya kamu yang bilang dulu, tidak semua yang kita tunggu akan datang?"</p><p>"Iya, aku bilang itu."</p><p>"Terus?"</p><p>Elang meletakkan cangkirnya. "Harapan bukan soal yakin sesuatu akan berhasil. Kalau definisinya itu, ya, percuma — karena kita memang tidak bisa tahu." Ia bersandar. "Harapan itu lebih seperti... keputusan untuk tetap membuka pintu. Meski tidak ada yang datang, pintunya tetap terbuka."</p><p>Rana diam. Di luar, hujan mengecil sedikit, tapi belum reda.</p><p>"Itu tidak melelahkan?"</p><p>"Melelahkan." Elang mengangguk pelan. "Tapi menutup pintu juga melelahkan, dengan cara yang berbeda. Bedanya, kalau ditutup — kamu bahkan tidak tahu apa yang kamu lewatkan."</p><p>Rana menoleh ke jendela. Ada genangan kecil di trotoar, memantulkan lampu toko yang kuning.</p><p>"Jadi kamu pilih capek yang mana?"</p><p>"Capek yang masih menyisakan kemungkinan," kata Elang.</p><p>Rana tidak menjawab. Tapi ia tidak menutup topik itu. Ia membiarkannya duduk di antara mereka — seperti pintu yang memang sengaja dibiarkan terbuka sedikit, agar udara tetap bisa masuk.</p>`},
  {date:'20 April 2025',title:'Marah Dulu',excerpt:'Setiap kali nonton yang kayak gini, rasanya campur aduk. Marah, tapi juga bingung. Mau ngapain? Mau ke mana?',body:`<p>Mereka duduk di teras kedai setelah tutup. Kursi-kursi sudah diangkat ke atas meja di dalam. Di luar, masih ada sisa gerimis.</p><p>Rana meletakkan ponselnya. Di layarnya, sebuah video panjang tentang penggusuran lahan di suatu desa. Warga menangis. Aparat berdiri dengan tameng.</p><p>"Aku," katanya, "setiap kali nonton yang kayak gini, rasanya campur aduk. Marah, tapi juga bingung. Mau ngapain? Mau ke mana? Mau lapor ke siapa?"</p><p>Elang menatap layar sebentar, lalu memandang gerimis.</p><p>"Terus jadinya enggak ngapa-ngapain?"</p><p>"Scroll terus. Nonton yang berikutnya. Ikut marah lagi. Lupa lagi." Rana menghela napas. "Kayak lingkaran yang enggak ke mana-mana."</p><p>"Itu karena kamu terlalu terburu-buru mau lompat ke solusi."</p><p>Rana mengernyit. "Memangnya kenapa kalau mau langsung cari solusi?"</p><p>"Karena rasa marah yang belum selesai, kalau dipaksa jadi tindakan, sering salah arah." Elang bersandar ke kursinya. "Marah dulu sampai tuntas. Pahami dulu apa yang bikin marah. Baru dari situ kelihatan mau ngapain."</p><p>"Tapi katanya kalau cuma marah, sama aja enggak berguna."</p><p>"Marah yang diam-diam, yang disimpan sendiri, yang habis itu dilupakan, iya. Tapi marah yang kamu sadari, yang kamu biarkan tinggal sebentar di dada sampai kamu benar-benar mengerti kenapa kamu marah, itu modal."</p><p>Rana mengambil ponselnya lagi. Menatap layar yang gelap.</p><p>"Jadi sekarang aku harus ngapain?"</p><p>Elang meliriknya sebentar. "Sekarang kamu sudah marah, kan?"</p><p>"Iya."</p><p>"Itu dulu sudah cukup."</p><p>Rana tidak menjawab. Tapi ia juga tidak membuka ponselnya lagi. Ia membiarkan gerimis itu berbunyi sebentar di atap sebelum akhirnya reda.</p>`},
  {date:'14 April 2025',title:'Orang Asing di Meja Sebelah',excerpt:'Ia selalu memesan kopi yang sama, duduk di sudut yang sama. Tapi hari itu ia menoleh — dan sesuatu berubah, meski tak ada yang bergerak.',body:`<p>Ia selalu datang pukul sembilan pagi, sebelum kafe ramai. Memesan americano tanpa gula, duduk di meja pojok dekat jendela, membuka buku yang sampulnya selalu berbeda. Selama tiga minggu, aku hafal rutinitasnya lebih baik dari rutinitasku sendiri.</p><p>Hari itu ia menoleh. Bukan karena aku menatap terlalu lama — setidaknya bukan hanya karena itu. Ada sesuatu yang jatuh dari mejanya, selembar kertas kecil, dan angin dari pintu yang terbuka menerbangkannya tepat ke sepatuku.</p><p>Aku memungutnya. Tulisan tangan, huruf kecil-kecil, sebuah daftar: <em>beli bawang, hubungi dokter, jangan lupa bahwa langit masih ada.</em></p><p>Aku mendongak. Ia sudah berdiri setengah dari kursinya, tangan terulur. Matanya seperti orang yang baru saja tertangkap basah melakukan sesuatu yang terlalu jujur untuk diakui.</p><p>"Terima kasih," katanya, tanpa menjelaskan daftar itu. Aku menyerahkan kertas itu kembali, juga tanpa bertanya.</p><p>Keesokan harinya ia tidak datang. Kursi pojok itu kosong, americano tidak dipesan, dan aku menyadari aku tidak tahu namanya.</p>`},
  {date:'2 Maret 2025',title:'Mengapa Kita Berhenti Membaca Perlahan',excerpt:'Di era notifikasi tak henti, membaca dengan sabar terasa seperti perlawanan kecil.',body:`<p>Ada sesuatu yang hilang ketika membaca menjadi kegiatan yang kita lakukan sambil melakukan hal lain. Buku di tangan, headphone di telinga, notifikasi bergetar di saku — kita hadir secara fisik di halaman, tapi pikiran kita sudah setengah perjalanan menuju tempat lain.</p><p>Membaca yang baik membutuhkan semacam kepercayaan. Kepercayaan bahwa penulis tahu ke mana ia membawa kita. Bahwa halaman yang terasa lambat bukan halaman yang sia-sia.</p><p>Membaca perlahan adalah bentuk kehadiran. Dan mungkin, di dunia yang terus meminta kita untuk bergerak lebih cepat, memilih untuk diam sejenak di dalam sebuah halaman adalah salah satu tindakan paling radikal yang masih bisa kita lakukan.</p>`},
  {date:'18 Februari 2025',title:'500 Kata Tentang Hujan Terakhir',excerpt:'Hujan itu datang tanpa pamit, seperti semua hal yang paling diingat.',body:`<p>Hujan itu datang tanpa pamit, seperti semua hal yang paling diingat. Ia membasahi trotoar dan percakapan yang tidak pernah selesai.</p><p>Kamu berdiri di bawah teras minimarket dengan plastik kresek di tangan. Aku berdiri di sebelahmu karena tidak ada tempat lain yang lebih masuk akal untuk berdiri.</p><p>Hujan akhirnya berhenti dua puluh menit kemudian. Kamu pergi ke kiri, aku ke kanan. Tidak ada yang mengatakan sesuatu yang penting.</p>`},
  {date:'5 Januari 2025',title:'Surat yang Tidak Pernah Dikirim',excerpt:'Tiga lembar kertas, tulisan tangan, tanda tangan yang ragu-ragu.',body:`<p>Tiga lembar kertas, tulisan tangan, tanda tangan yang ragu-ragu di bagian bawah halaman terakhir. Ia melipatnya tiga kali, memasukkannya ke amplop, menulis alamat yang sudah ia hafal sejak dua belas tahun lalu.</p><p>Surat itu ditulis pada suatu Minggu sore di bulan November, ketika hujan terlalu lebat untuk keluar dan terlalu ramai untuk berpikir jernih.</p><p>Bertahun-tahun kemudian, ia menemukan amplop itu lagi. Ia membukanya. Membaca semuanya. Lalu melipat kembali dengan hati-hati.</p>`},
  {date:'12 Desember 2024',title:'Ruang Tunggu',excerpt:'Semua orang di sini sedang menunggu sesuatu. Tapi tidak ada yang bicara tentang apa.',body:`<p>Ruang tunggu rumah sakit punya cahaya yang tidak menyenangkan siapa pun. Terlalu terang untuk nyaman, terlalu dingin untuk tenang.</p><p>Di sebelahku, seorang perempuan tua membuka dan menutup ritsleting tasnya berulang kali. Suaranya seperti detak jam yang tidak presisi.</p><p>Nama dipanggil satu per satu. Orang-orang berdiri, mengumpulkan barang-barang mereka, pergi ke balik pintu putih.</p>`},
  {date:'3 November 2024',title:'Tentang Orang-Orang yang Kita Lupakan',excerpt:'Ada wajah-wajah yang pernah kita kenal, lalu perlahan menghilang dari ingatan.',body:`<p>Kadang aku tiba-tiba teringat seseorang yang sudah bertahun-tahun tidak aku pikirkan. Teman sebangku kelas empat SD. Tetangga yang selalu menyapu teras di pagi hari.</p><p>Mereka pernah ada dalam hidupku — benar-benar ada, dalam cara yang nyata dan konkret. Kita berbagi ruang, berbagi waktu, mungkin berbagi beberapa patah kata.</p>`},
  {date:'20 Oktober 2024',title:'Kota Setelah Tengah Malam',excerpt:'Ada versi lain dari kota ini yang hanya bisa dilihat setelah semua orang tidur.',body:`<p>Aku sering berjalan sendirian setelah tengah malam. Ada sesuatu tentang kota yang kosong yang membuatnya terasa lebih jujur.</p><p>Ada jembatan yang selalu aku lewati. Di siang hari ia biasa saja. Tapi malam hari, dengan lampu pantulan di air, ia terasa seperti ambang batas antara dua dunia yang tidak punya nama.</p>`},
  {date:'8 September 2024',title:'Percakapan yang Tidak Selesai',excerpt:'Beberapa kalimat tidak pernah menemukan akhirnya.',body:`<p>Ada percakapan tertentu yang berhenti di tengah — bukan karena salah satu pihak memutuskan untuk berhenti, tapi karena sesuatu di luar kita memotong sebelum selesai.</p><p>Aku punya beberapa. Percakapan dengan seseorang yang meninggal sebelum aku sempat berkata apa yang seharusnya aku katakan.</p>`},
  {date:'15 Agustus 2024',title:'Di Bawah Pohon yang Sama',excerpt:'Setiap tahun aku kembali ke tempat yang sama. Pohonnya tetap ada. Tapi aku selalu berbeda.',body:`<p>Ada pohon di sudut taman dekat rumah masa kecilku. Ketika kecil, aku pikir pohon itu sangat tua. Sekarang, setelah dua puluh tahun, aku baru sadar bahwa pohon itu mungkin tidak setua yang aku kira.</p><p>Yang berbeda adalah aku. Aku membawa lebih banyak hal sekarang — lebih banyak tahun, lebih banyak kehilangan, lebih banyak pertanyaan yang tidak terjawab.</p>`},
  {date:'1 Juli 2024',title:'Memasak untuk Satu Orang',excerpt:'Ada kesedihan kecil yang tidak dramatis dalam memasak untuk diri sendiri.',body:`<p>Aku mulai belajar memasak ketika tinggal sendirian untuk pertama kalinya. Bukan karena aku suka memasak — lebih karena makan mi instan setiap hari mulai terasa seperti cara paling lambat untuk menyerah pada hidup.</p><p>Lama-lama aku menemukan sesuatu di dalamnya. Ketika tidak ada yang menonton, kamu bisa memasak persis seperti yang kamu mau.</p>`},
  {date:'14 Juni 2024',title:'Buku yang Tidak Selesai Dibaca',excerpt:'Di rakku ada beberapa buku yang tidak pernah sampai halaman terakhir.',body:`<p>Ada buku di rakku yang sudah terbuka sampai halaman 73 selama hampir dua tahun. Pembatasnya masih di sana — sehelai struk belanja yang sudah memudar.</p><p>Mungkin tidak semua buku perlu diselesaikan. Mungkin 73 halaman itu sudah memberikan apa yang perlu diberikan pada saat itu.</p>`},
  {date:'22 Mei 2024',title:'Orang yang Kita Jadi di Kota Lain',excerpt:'Ada versi dari diri kita yang hanya muncul ketika tidak ada yang mengenal kita.',body:`<p>Pertama kali aku menyadarinya di Yogyakarta. Aku ke sana sendirian, tidak kenal siapapun, dan dalam dua hari pertama aku berbicara kepada orang-orang asing dengan cara yang tidak pernah aku lakukan di kota sendiri.</p>`},
];

var allBooks=[
  {title:'Jumpa Lagi di Surga',cat:'Novel',year:2026,pages:312,blurb:`<p>Sebuah novel tentang pertemuan yang tidak pernah kita rencanakan — dan perpisahan yang selalu datang terlalu cepat.</p>`,reviews:[{stars:5,text:'Saya menangis di halaman terakhir.',name:'Laila R., Goodreads'},{stars:5,text:'Nurunala menulis cinta seperti orang yang benar-benar pernah kehilangan.',name:'Dimas A., Goodreads'},{stars:4,text:'Novel yang akan kamu baca dua kali.',name:'Sari W., Goodreads'}]},
  {title:'Seribu Wajah Ayah',cat:'Novel',year:2026,pages:284,blurb:`<p>Novel yang menjelajahi hubungan antara seorang anak dan ayahnya.</p>`,reviews:[{stars:5,text:'Ini bukan hanya tentang ayah.',name:'Rani P., Goodreads'},{stars:5,text:'Seperti membuka foto lama.',name:'Bagas T., Goodreads'},{stars:4,text:'Membuat saya menelepon ayah malam itu juga.',name:'Indah S., Goodreads'}]},
  {title:'Janji untuk Ayah',cat:'Novel',year:2024,pages:256,blurb:`<p>Novel tentang seorang perempuan yang tumbuh bersama satu janji yang tidak pernah ia lupakan.</p>`,reviews:[{stars:5,text:'Menepati janji kadang artinya melepaskan.',name:'Maya K., Goodreads'},{stars:4,text:'Seperti sungai yang kelihatan dangkal tapi ternyata tidak.',name:'Rizal H., Goodreads'},{stars:4,text:'Karakter utamanya terasa sangat nyata.',name:'Dewi L., Goodreads'}]},
  {title:'Festival Hujan',cat:'Novel',year:2024,pages:298,blurb:`<p>Dua orang bertemu setiap tahun selama sepuluh tahun. Novel tentang ritme yang kita ciptakan dengan orang lain.</p>`,reviews:[{stars:5,text:'Romantis tanpa sentimentalitas berlebihan.',name:'Citra M., Goodreads'},{stars:5,text:'Setiap bab terasa seperti satu musim hujan.',name:'Eko P., Goodreads'},{stars:4,text:'Novel tentang waktu yang paling jujur.',name:'Nisa F., Goodreads'}]},
  {title:'Jangan Dulu Patah',cat:'Kumpulan Cerita',year:2023,pages:188,blurb:`<p>Dua belas cerita tentang orang-orang yang sedang belajar bertahan.</p>`,reviews:[{stars:5,text:'Terasa seperti surat dari teman yang sangat mengenal kamu.',name:'Fitri A., Goodreads'},{stars:4,text:'Favorit saya adalah cerita keempat.',name:'Hendra B., Goodreads'},{stars:5,text:'Menulis kesakitan dengan sangat lembut.',name:'Yuni S., Goodreads'}]},
  {title:'Di Antara Dua Musim',cat:'Kumpulan Cerita',year:2023,pages:162,blurb:`<p>Sepuluh cerita di musim-musim peralihan — tentang ambang batas dan keberanian untuk melangkah.</p>`,reviews:[{stars:4,text:'Seperti potret sesaat yang menangkap hal yang biasanya terlewat.',name:'Arum D., Goodreads'},{stars:5,text:'Saya membacanya pelan-pelan supaya tidak cepat habis.',name:'Gilang R., Goodreads'},{stars:4,text:'Koleksi yang konsisten.',name:'Putri N., Goodreads'}]},
  {title:'Pulang ke Mana',cat:'Sajak',year:2022,pages:96,blurb:`<p>Kumpulan sajak tentang rumah — bukan sebagai tempat, tapi sebagai perasaan.</p>`,reviews:[{stars:5,text:'Sajak-sajaknya pendek tapi berat.',name:'Reza M., Goodreads'},{stars:5,text:'Tahu persis berapa berat sebuah kata.',name:'Tiara K., Goodreads'},{stars:4,text:'Buku tipis yang terasa tebal.',name:'Adi W., Goodreads'}]},
  {title:'Ruang di Antara Kata-Kata',cat:'Kumpulan Cerita',year:2022,pages:204,blurb:`<p>Kumpulan cerpen pertama Azhar Nurunala. Delapan cerita tentang hal-hal yang tidak terucapkan.</p>`,reviews:[{stars:5,text:'Debut yang luar biasa.',name:'Lestari B., Goodreads'},{stars:4,text:'Sangat matang untuk sebuah buku pertama.',name:'Fauzan A., Goodreads'},{stars:5,text:'Cerita pertama saja sudah membuat saya tidak bisa berhenti.',name:'Mega S., Goodreads'}]},
  {title:'Catatan dari Kota yang Lupa Tidur',cat:'Kumpulan Cerita',year:2022,pages:176,blurb:`<p>Catatan dari kota yang tidak pernah benar-benar tidur.</p>`,reviews:[{stars:4,text:'Urban dan personal sekaligus.',name:'Wahyu P., Goodreads'},{stars:5,text:'Pengalaman yang tidak terlupakan.',name:'Dina R., Goodreads'},{stars:4,text:'Sangat Jakarta, tapi juga sangat manusia.',name:'Budi S., Goodreads'}]},
  {title:'Seperti Daun Jatuh',cat:'Sajak',year:2021,pages:88,blurb:`<p>Sajak-sajak tentang kepergian yang perlahan.</p>`,reviews:[{stars:5,text:'Melankolis tapi tidak muram.',name:'Yanti H., Goodreads'},{stars:5,text:'Untuk siapa pun yang sedang kehilangan.',name:'Surya K., Goodreads'},{stars:4,text:'Diksi yang dipilih dengan sangat hati-hati.',name:'Nanda L., Goodreads'}]},
  {title:'Segala yang Tersisa Setelah Hujan',cat:'Sajak',year:2021,pages:104,blurb:`<p>Sajak-sajak tentang apa yang tertinggal setelah badai berlalu.</p>`,reviews:[{stars:5,text:'Membuat hal yang sederhana terasa sakral.',name:'Ira M., Goodreads'},{stars:4,text:'Yang terbaik yang pernah saya baca dalam bahasa Indonesia.',name:'Bayu T., Goodreads'},{stars:5,text:'Saya membaca buku ini tiga kali dalam seminggu.',name:'Clara N., Goodreads'}]},
  {title:'Sebelum Kamu Pergi',cat:'Novel',year:2020,pages:240,blurb:`<p>Novel debut Azhar Nurunala. Tentang dua orang yang memilih untuk tetap ada, selagi bisa.</p>`,reviews:[{stars:5,text:'Dari novel pertama sudah terlihat betapa talentednya penulis ini.',name:'Rina K., Goodreads'},{stars:4,text:'Ending yang berani.',name:'Toni A., Goodreads'},{stars:5,text:'Menangis di toilet supaya tidak membangunkan siapapun.',name:'Wati S., Goodreads'}]},
];

function slugify(s){ return s.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,''); }
function qp(name){ return new URLSearchParams(location.search).get(name); }
